server {
    listen 443 ssl;
    server_name www.kalendarium.it;
    ssl_certificate /etc/letsencrypt/live/www.kalendarium.it/fullchain.pem; # managed by Certbot
    ssl_certificate_key /etc/letsencrypt/live/www.kalendarium.it/privkey.pem; # managed by Certbot

    return 301 https://kalendarium.it$request_uri;

}

server {
    listen 80;
    server_name kalendarium.it;
    return 301 https://$host$request_uri;
}

server {
    listen 443 ssl;
    server_name kalendarium.it;
    client_max_body_size 25M;

    ssl_certificate /etc/letsencrypt/live/kalendarium.it/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/kalendarium.it/privkey.pem;

    location ~* ^/(css|js|fonts|images|storage|build)/ {
        root /var/www/Kalendarium/public;
        try_files $uri =404;
        expires 1y;
    }

    location /api/ {
        client_max_body_size 25M;
        fastcgi_pass unix:/var/run/php/php8.4-fpm.sock;
        fastcgi_param SCRIPT_FILENAME /var/www/Kalendarium/public/index.php;
        fastcgi_param REQUEST_URI $request_uri;
        fastcgi_param DOCUMENT_ROOT /var/www/Kalendarium/public;
        include fastcgi_params;
    }

    location /filament-admin {
        fastcgi_pass unix:/var/run/php/php8.4-fpm.sock;
        fastcgi_param SCRIPT_FILENAME /var/www/Kalendarium/public/index.php;
        fastcgi_param REQUEST_URI $request_uri;
        fastcgi_param DOCUMENT_ROOT /var/www/Kalendarium/public;
        include fastcgi_params;
    }

    location /livewire {
        fastcgi_pass unix:/var/run/php/php8.4-fpm.sock;
        fastcgi_param SCRIPT_FILENAME /var/www/Kalendarium/public/index.php;
        fastcgi_param REQUEST_URI $request_uri;
        fastcgi_param DOCUMENT_ROOT /var/www/Kalendarium/public;
        include fastcgi_params;
    }

    location /assets/ {
        root /var/www/Kalendarium/frontend/dist;
        expires 1y;
        add_header Cache-Control "public, immutable";
    }

    location / {
        root /var/www/Kalendarium/frontend/dist;
        try_files $uri $uri/ /index.html;

        location = /index.html {
            add_header Cache-Control "no-cache, no-store, must-revalidate";
        }
    }
}
server {
    if ($host = www.kalendarium.it) {
        return 301 https://$host$request_uri;
    } # managed by Certbot


    listen 80;
    server_name www.kalendarium.it;
    return 404; # managed by Certbot


}
